#=============================================================================================================
#Temperature

### Create Data
POST  http://localhost:8080/komposter/addData/temperatures
Accept: application/json
Content-Type: application/json

{
    "value": "37.3"
}

### Get Data
GET http://localhost:8080/komposter/data/temperatures/b6eab927-b6a1-442d-8587-15be841dea4a
Accept: application/json

### Get All Data
GET http://localhost:8080/komposter/data/temperatures
Accept: application/json

### Update Data
PATCH http://localhost:8080/komposter/update/temperatures/b6eab927-b6a1-442d-8587-15be841dea4a
Accept: application/json
Content-Type: application/json

{
    "value": "35.6"
}

### Delete Data
DELETE  http://localhost:8080/komposter/delete/temperatures/b6eab927-b6a1-442d-8587-15be841dea4a
Accept: application/json

#=============================================================================================================
#Moisture

### Create Data
POST  http://localhost:8080/komposter/addData/moistures
Accept: application/json
Content-Type: application/json

{
    "value": "42.3"
}

### Get Data
GET http://localhost:8080/komposter/data/moistures/974f6130-1998-4f0e-9c86-3645bfcd7b47
Accept: application/json

### Get All Data
GET http://localhost:8080/komposter/data/moistures
Accept: application/json

### Update Data
PATCH http://localhost:8080/komposter/update/moistures/974f6130-1998-4f0e-9c86-3645bfcd7b47
Accept: application/json
Content-Type: application/json

{
    "value": "45.6"
}

### Delete Data
DELETE  http://localhost:8080/komposter/delete/moistures/043a1265-bd10-44a9-8a28-cc1fa32d12e5
Accept: application/json

#=============================================================================================================
#PhMeter

### Create Data
POST  http://localhost:8080/komposter/addData/phMeters
Accept: application/json
Content-Type: application/json

{
    "value": "2.3"
}

### Get Data
GET http://localhost:8080/komposter/data/phMeters/b021ce4b-bbff-44ac-ac90-5e6056483ae6
Accept: application/json

### Get All Data
GET http://localhost:8080/komposter/data/phMeters
Accept: application/json

### Update Data
PATCH http://localhost:8080/komposter/update/phMeters/b021ce4b-bbff-44ac-ac90-5e6056483ae6
Accept: application/json
Content-Type: application/json

{
    "value": "2.6"
}

### Delete Data
DELETE  http://localhost:8080/komposter/delete/phMeters/b021ce4b-bbff-44ac-ac90-5e6056483ae6
Accept: application/json